plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.2'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.doogoo'
version = '0.0.1-SNAPSHOT'
description = '두구두구 백엔드'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// 스프링부트트
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'


	// ICS 캘린더
	implementation 'org.mnode.ical4j:ical4j:4.2.3'

	// 웹 크롤링
	implementation 'org.jsoup:jsoup:1.18.1'

	// DB
	runtimeOnly 'org.postgresql:postgresql'
	runtimeOnly 'com.h2database:h2'
	implementation 'org.flywaydb:flyway-core'
	implementation 'org.flywaydb:flyway-database-postgresql'

	// API 문서 (Swagger)
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.1'

	// 테스트코드 (JUnit 5 + MockMvc)
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
